# Cloud Build configuration for Google Cloud Run
# Usage: gcloud builds submit --config cloudbuild.yaml .
#
# Required substitutions (set via --substitution-args or trigger config):
#   _REGION          – Cloud Run region  (default: us-central1)
#   _SERVICE_NAME    – Cloud Run service (default: rr-foam-pro)
#   _GEMINI_API_KEY  – (optional) Gemini API key baked into the build

substitutions:
  _REGION: us-central1
  _SERVICE_NAME: rr-foam-pro
  _GEMINI_API_KEY: ""

steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "--build-arg"
      - "GEMINI_API_KEY=${_GEMINI_API_KEY}"
      - "-t"
      - "gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA"
      - "-t"
      - "gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest"
      - "."

  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA"

  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest"

  # Deploy to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "${_SERVICE_NAME}"
      - "--image"
      - "gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA"
      - "--region"
      - "${_REGION}"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--port"
      - "8080"
      - "--memory"
      - "256Mi"
      - "--cpu"
      - "1"
      - "--min-instances"
      - "0"
      - "--max-instances"
      - "3"
      - "--concurrency"
      - "80"

images:
  - "gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA"
  - "gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest"

timeout: "1200s"
